# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI build

on:
  push:
    branches: [ master ]

jobs:
  cases_generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
        
      - run: python gen_cases.py
        name: Generate cases in generated dir
      
      - name: Upload generated cases
        uses: actions/upload-artifact@v2
        with:
          name: generated_cases
          path: generated
  
  cases_deploy:
    needs: cases_generate
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Fetch generated cases
        uses: actions/download-artifact@v2
        with:
          name: generated
          path: artifacts/generated
      
      - name: Copy generated files to generation dir
        run: cp -R artifacts/generated/* generation/gh-pages/
      
      - name: Deploy cases to Github Pages
        uses: crazy-max/ghaction-github-pages@v2.0.0
        with:
          target_branch: gh-pages
          keep_history: true
          allow_empty_commit: false
          build_dir: "generation/gh-pages"
          author: "ci-build <ci-build@agoranomic.org>"
          commit_message: "[skip ci] CI Updates"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
